services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: container:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TORRENTING_PORT=6881
      - WEBUI_PORT=8080
    volumes:
      - /home/user/Mediaconfig/qbittorrent/appdata/:/config
      - /home/user/Media/downloads:/downloads #optional
      - /home/user/Media/Movies:/movies #optional
      - /home/user/Media/Series:/series #optional
    labels:
      - traefik.enable=true
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
